### ISSUE TITLE
Discussion: remove `mode = "n"` in `lsp.nix`

### ISSUE THREAD

**Issue by ugur-a** [JMartJonesy/kickstart.nixvim#5]
I'm talking about options like this:
https://github.com/JMartJonesy/kickstart.nixvim/blob/b7e044cdffc6c8b356b57cd69665e0f5636826fd/plugins/lsp.nix#L208-L212
Nixvim, at least currently, forces these keymaps to be in Normal mode by using the following helper function in `config.keymapsOnEvents.LspAttach`:
https://github.com/nix-community/nixvim/blob/6dc0bda459bcfb2a38cf7b6ed1d6a5d6a8105f00/plugins/lsp/default.nix#L188-L205

so
a) `mode = "n"` is redundant
b) no other mode can't be set anyway

**Comment by JMartJonesy** [comment]
Removed in https://github.com/JMartJonesy/kickstart.nixvim/commit/2cab3a1379a1d2a4b5cad03d3e6e279795408f3a
