### ISSUE TITLE
Turn this repository into a nixvim standalone flake template

### ISSUE THREAD

**Issue by HeitorAugustoLN** [JMartJonesy/kickstart.nixvim#6]
I think it would be better if this repository was a nixvim standalone flake template, just like kickstart.nvim is a template for a neovim configuration. I might do a PR to a nixvim standalone flake.

**Comment by JMartJonesy** [comment]
I'm quite new to flakes. A few questions.

If you use a flake for your entire NixOS configuration or for home-manager what would need to be done to also build this flake at the same time?

Nix flakes are still classified as experimental, if you didn't want to enable them would there be any issue with forking and not using the flake but rather importing as the README already details?

**Comment by HeitorAugustoLN** [comment]
> If you use a flake for your entire NixOS configuration or for home-manager what would need to be done to also build this flake at the same time?

You will need to add this flake to your inputs, and then you add the package the flake exports to environment.systemPackages or home.packages

> Nix flakes are still classified as experimental, if you didn't want to enable them would there be any issue with forking and not using the flake but rather importing as the README already details?

No, it can be imported as normal

**Comment by JMartJonesy** [comment]
I'll have to think about this when I have the time. My first thought is we make this a separate branch and anyone that wants standalone can use this branch with an updated README.

**Comment by HeitorAugustoLN** [comment]
I think the default branch should be the nixvim standalone flake template, but I don't think it really matters that much.

**Comment by JMartJonesy** [comment]
I have made a separate branch named standalone for flak installation https://github.com/JMartJonesy/kickstart.nixvim/tree/standalone. https://github.com/JMartJonesy/kickstart.nixvim/tree/standalone

**Comment by no-mood** [comment]
Would it be possible to add the reference to the branch in the readme? I was about to open another issue when I read this here :)
Otherwise I wouldn't have noticed
